### ISSUE TITLE
Nothing happening...

### ISSUE THREAD

**Issue by rlayne** [Djdefrag/QualityScaler#1]
Unfortunately the app just sits there consuming a little CPU but otherwise not touching the GPU or the input image for all variations of options on a 300x300 jpg.

Please add logging, and more detailled in-app status/progress signage so I can submit something more useful. 
Running on Win10, all CUDA libraries installed, it's my deep learning research box.

**Comment by Djdefrag** [comment]
Hi, can you tell exactly what appens? 

The app has built in cuda libraries in the dir, so i suppose it's not the problem  :)

If some error happens during the upscale there is an error message. Did you see it?

If the app says "upscale completed" it means that in the same directory of the original file there is the upscaled file. Did you checked? 

Thanks for the feedback :)

**Comment by rlayne** [comment]
There were no messages of any kind I'm afraid, literally nothing happens for me for the ten minutes I gave it, otherwise I would have mentioned.
I assumed the file would be in the same directory due to lack of path field, but no, nothing there either.

**Comment by Djdefrag** [comment]
Really strange, but thank you for the feedback. I will improve the this part of the app :)

What hardware are you using? Cpu, Gpu etc"?

Did you also tried cpu? Just to have this bit of information :)

**Comment by rlayne** [comment]
rtx3080ti and i8700k.
cpu mode seems to work albeit expectedly slow

**Comment by Djdefrag** [comment]
Perfect! Probably the problem is the cuda version in the app: sadly cuda 10.2 (the one used) is not compatible with Nvidia 3k. 
I will update to cuda 11 ASAP. 

Thank you very much  for the feedback, without it I would never have known about this problem because I currently cannot afford a Nvidia 3k :)

**Comment by rlayne** [comment]
Ah, that sounds about right. Ironically I only just got around to plugging this thing in to replace my previous 2x1080ti setup.  I have another machine with an rtx2080ti in it, I'll shout if I get a chance to try it on there.

People are saying the 30xx series are coming back into stock without the crazy price hikes, so hopefully you can snag one soon but it you want to try just blindly including the relevant libs and redeploying I'll let you know if it works :)

**Comment by Djdefrag** [comment]
Thank you! 
I really appreciate your help!  I will build the app with cuda 11 and i will leave a link to download as soon as ready.

Hope so. Finally a good news about prices :D

**Comment by Djdefrag** [comment]
1.4.0alpha (1.3.0 + cuda 11.1)

link-> https://www.dropbox.com/s/he7u33egxvk7um1/QualityScaler_1.4.0alpha.zip?dl=0

let me know if you try :D

**Comment by rmast** [comment]
I downgraded the Tesla-driver to CUDA 10.2. Still no GPU-performance. Indeed no logging at all about what's wrong. Should I download the exact CUDA 11 version?

**Comment by rmast** [comment]
I could try download old version 1.3.0 to match CUDA 10.2, or upgrade the CUDA driver to 11.1 or 11.3 and try 1.4.0 resp. 1.5.0.

**Comment by rmast** [comment]
Yes!

![image](https://user-images.githubusercontent.com/3341558/177057088-cf0c7d6a-e7ff-4ad8-9330-4bd48d565a7e.png)

**Comment by rmast** [comment]
There is no Tesla 11.3 driver or 11.1 driver, so them I'm probably only able to run the old 10.2 versions.

![image](https://user-images.githubusercontent.com/3341558/177057302-6543e6d1-0bf6-483b-ac93-99f5cf4ab8ec.png)

**Comment by Djdefrag** [comment]
OK! 
So I suppose the driver is not DirectX12 compatible that is why does not work with Pytorch-directml.

**Comment by rmast** [comment]
The K80 supports DirectX 12, so that shouldn't be the problem. If you replaced CUDA by DirectML in version 2.20. I could try the CUDA-11 versions with drivers nearby.

Outlook voor Android downloaden<https://aka.ms/ghei36>
________________________________

**Comment by Djdefrag** [comment]
If it fully supported Directx12 the app should work with DirectML, maybe the documentation reports wrong information
