### ISSUE TITLE
Specs probably too small

### ISSUE THREAD

**Issue by rmast** [Djdefrag/QualityScaler#10]
I have an old AMD X4 646 and 16GB. Running with CPU did not hog the CPU, so something went wrong.

My father has a new Windows 11 PC with 8GB. Running with CPU did not hog the CPU, so something went wrong.

Finally I decided to rent a Azure NC6_Promo with K80 cuda. That does the job after a reboot for installing the K80.

**Comment by rmast** [comment]
Even on that near empty K80 8GB is just too short
![image](https://user-images.githubusercontent.com/3341558/177014158-7d3f9d06-9f87-47ff-9ea8-8737b773910c.png)

**Comment by rmast** [comment]
It's already running more than an hour on quadrupalizing a 300 dpi A4, so the 6 core K80 is no luxury.

**Comment by rmast** [comment]
After one and a half hour the memory footprint has more than doubled:
![image](https://user-images.githubusercontent.com/3341558/177016101-4b8276a0-98c8-4c12-b949-0dd1f5583577.png)

**Comment by rmast** [comment]
Next morning still a bit more memory... Glad I disabled Windows update...
![image](https://user-images.githubusercontent.com/3341558/177024221-e66e8177-03b5-4080-880a-88f2eee54866.png)

**Comment by rmast** [comment]
Used memory still growing a bit:
![image](https://user-images.githubusercontent.com/3341558/177030228-bec14f8b-2e95-4d3e-948d-800051dfd357.png)

**Comment by Djdefrag** [comment]
Wow! Thank you for the comprehensive tests that you did! 
I suppose that Pytorch-directml is not well optimized with CPU, in my tests i found that even when i set more cpus, it just use 1. The only thing i can say is that this library is still in alpha state, so maibe in future will be better optimized.

:D

**Comment by rmast** [comment]
The K80 contains a GPU, with CUDA codes sm_30, sm_35 and sm_37. It might be ignored by the used software.

**Comment by Djdefrag** [comment]
Yes, sadly the library just ignore this GPU

**Comment by rmast** [comment]
How long do you estimate a 300 dpi A4 will take with only 6 cores?

**Comment by rmast** [comment]
Do you know an Azure VM which supports DirectML?

**Comment by Djdefrag** [comment]
I estimate from 15 to 30 minutes

**Comment by Djdefrag** [comment]
Sorry, i m not pratical with Azure stuff

**Comment by rmast** [comment]
DirectML should support Kepler according to the readme:
https://github.com/microsoft/DirectML

**Comment by Djdefrag** [comment]
Yes, but i suppose maibe they refers to commercial GPUs like GTX

**Comment by Djdefrag** [comment]
Just to be sure, can you try first a x0.5 upscale or x1 to check if everything works fine, this must be quick

**Comment by rmast** [comment]
Just broke off the long run and started x0.5

**Comment by Djdefrag** [comment]
oook thanks, i was thinking did you installed nvidia drivers on the vm?

**Comment by rmast** [comment]
Should the tool nvidia-smi be on Windows? It can't find it.

**Comment by rmast** [comment]
There was a popup stating K80 driver installed.

**Comment by rmast** [comment]
I'm now installing the Tesla-driver from the Nvidia-site.

**Comment by Djdefrag** [comment]
yes, maibe that will do the catch because when you screened the task manager i saw that there was no GPU panel. That usually happen when the driver is not installed

**Comment by rmast** [comment]
> yes, maibe that will do the catch because when you screened the task manager i saw that there was no GPU panel. That usually happen when the driver is not installed

That feature only works with WDDM 2.0 I understand from this video.
https://www.youtube.com/watch?v=gOo73cyeMUU

The K80 has 1.3.

![image](https://user-images.githubusercontent.com/3341558/177032765-5bd5130f-426c-480e-b8c2-35c56f0b2685.png)

**Comment by rmast** [comment]
I've restarted the x1 upscale after a reboot. nvidia-smi responds.
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 473.47       Driver Version: 473.47       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           TCC  | 00000001:00:00.0 Off |                    0 |
| N/A   32C    P8    35W / 149W |      9MiB / 11448MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
CPU is high, nvidia-smi states "No running processes found"

**Comment by Djdefrag** [comment]
Really strange, so if you upscale on gpu it does nothing?

**Comment by Djdefrag** [comment]
Ah, also did you try install all Visual Studio runtimes?
https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

**Comment by rmast** [comment]
I'm downloading/uploading those other VC runtimes.
There might be some truth in this thread:
https://discuss.pytorch.org/t/ubuntu-what-version-of-cuda-pytorch-etc-can-run-on-a-nvidia-gtx-680-compute-capability-3-0/118469/4

The files mention 3.7, however there might be some issues with 3.7. The Tesla-driver I downloaded is supporting Cuda 11.4, so that might be introducing other issues.
