### ISSUE TITLE
Error : float division by zero

### ISSUE THREAD

**Issue by FR3NCHCORE** [Djdefrag/QualityScaler#100]
Hi,

I'm trying to upscale a video from a personal DVD rip.
After 12h of work, I get this error at the end of the job.

" Upscale error, please report the error on Github : float division by zero "

Let me know if u need more infos or logs.

![Capture d’écran 2024-09-05 075948](https://github.com/user-attachments/assets/ebc8a15b-30c6-4081-a353-f33e0daacab8)

**Comment by Djdefrag** [comment]
Hi my friend,

can you try again with the same settings? 

QualityScaler will resume from the interrupted point (if you have not deleted the files)

**Comment by FR3NCHCORE** [comment]
> Hi my friend,
> 
> can you try again with the same settings?
> 
> QualityScaler will resume from the interrupted point (if you have not deleted the files)

Even if I've already restart my computer ?
I will try so and let u know.

**Comment by Djdefrag** [comment]
Yes, even if you restarted the pc

QualityScaler saves upscaled video frames in a directory, so nothing is lost :)

**Comment by FR3NCHCORE** [comment]
> Yes, even if you restarted the pc
> 
> QualityScaler saves upscaled video frames in a directory, so nothing is lost :)

The rendering has resumed, I will keep you informed.

**Comment by Djdefrag** [comment]
okk, let me know my friend

Probably you need to download new version of ffmpeg.exe and put it in QualityScaler/Assets folder.

1. Go to this site (https://www.gyan.dev/ffmpeg/builds/)
2. Download one of this zip
![359510912-465cb92a-8850-4445-8025-02db15b25789](https://github.com/user-attachments/assets/358e9543-13ff-4a1c-bbbb-134ef05d98a8)
3. Extract ffmpeg.exe from the downloaded .zip
4. Copy ffmpeg.exe to QualityScaler/Assets

unfortunately I can't upload the new version to github because it weighs too much and github won't let me

**Comment by FR3NCHCORE** [comment]
> okk, let me know my friend
> 
> Probably you need to download new version of ffmpeg.exe and put it in QualityScaler/Assets folder.
> 
>     1. Go to this site (https://www.gyan.dev/ffmpeg/builds/)
> 
>     2. Download one of this zip
>        ![359510912-465cb92a-8850-4445-8025-02db15b25789](https://private-user-images.githubusercontent.com/32263112/364706459-358e9543-13ff-4a1c-bbbb-134ef05d98a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1Mjc5MTksIm5iZiI6MTcyNTUyNzYxOSwicGF0aCI6Ii8zMjI2MzExMi8zNjQ3MDY0NTktMzU4ZTk1NDMtMTNmZi00YTFjLWJiYmItMTM0ZWYwNWQ5OGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDA5MTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4ZmNmNWU2YjM0MDg3ODM1NTExMzgyOTM3NjM0NzMyYzU0ZWI0Y2FiNWE1NDg2YzJlZWQxY2U0NWQzZWZhMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GunAwPIXw856DhjG5oJ7HAkxvvoyyxf2FF7ImHf2s-A)
> 
>     3. Extract ffmpeg.exe from the downloaded .zip
> 
>     4. Copy ffmpeg.exe to QualityScaler/Assets
> 
> 
> unfortunately I can't upload the new version to github because it weighs too much and github won't let me

This time it finish without error.
I didnt need to update ffmpeg.

thx u.

**Comment by Djdefrag** [comment]
Perfect my friend!
