### ISSUE TITLE
Download link in https://gofile.io/d/hIOmMc is not reachable.

### ISSUE THREAD

**Issue by ashwaniarya** [Djdefrag/QualityScaler#102]
I am trying to download the ai_onnx model from website but the site always says unreachable. Any one have other link to download the model?

**Comment by Djdefrag** [comment]
Hi my friend,

are you using https://gofile.io/d/hIOmMc ?

I can download without problem

![image](https://github.com/user-attachments/assets/65047993-a777-45d1-a9c0-3bba64cbf360)
