### ISSUE TITLE
WARNING: Ignoring invalid distribution ~ip (C:\Python312\Lib\site-packages)

### ISSUE THREAD

**Issue by Hifilo** [Djdefrag/QualityScaler#103]
Hi Djdefrag,

I havent used this in a while, so i went to update. Having some issues w the requirements.

```WARNING: Ignoring invalid distribution ~ip (C:\Python312\Lib\site-packages)```

![WindowsTerminal_jhfe4ljpiX](https://github.com/user-attachments/assets/e8a28f24-c0d2-4776-bdbc-ed5e3e97fe94)

Can you elaborate on this issue? I was updating from 2.11.  Perhaps the issue is on my end since I haven't used python in a while.

Cheers.

Edit: it appears to be running through the program without any issues or warnings, so maybe this is a non issue.

Cheers,

**Comment by Djdefrag** [comment]
Perfect my friend!
