### ISSUE TITLE
Readme typo

### ISSUE THREAD

**Issue by DaiterGG** [Djdefrag/QualityScaler#108]
At least on windows, command from the guide doesn't work without extension
![2024-11-13 04_14_22-requirements txt - QualityScaler-main - Visual Studio Code  Administrator](https://github.com/user-attachments/assets/b2b34fcd-8e90-4f30-8cfe-abd7c7d3ef4b)

**Comment by Djdefrag** [comment]
Thank you my friend, 

fixed :)
