### ISSUE TITLE
x1 upscale of nicely printed form isn't looking that fancy

### ISSUE THREAD

**Issue by rmast** [Djdefrag/QualityScaler#11]
Source:
![175789293-f39ddfdb-6f3e-4598-8d16-80a1f4a88b36](https://user-images.githubusercontent.com/3341558/177034309-cadc08a4-4787-48aa-b712-659061e3a309.jpg)

Result:
![175789293-f39ddfdb-6f3e-4598-8d16-80a1f4a88b36_BSRGAN_x1](https://user-images.githubusercontent.com/3341558/177034290-07b61c35-3844-4444-b9d1-e9c3465f1c19.jpg)

**Comment by Djdefrag** [comment]
x1 and x0.5 are usefull for really big images. But at least we know that the app works, you can try now x2 it will be much better

**Comment by rmast** [comment]
If x1 is that bad compared with x2 it shouldn't be offered. I didn't get CUDA do it's job. I didn't try my last hint on that subject. That quality loss at x1 is not motivating further testing.

Outlook voor Android downloaden<https://aka.ms/ghei36>
________________________________

**Comment by Djdefrag** [comment]
It can be used for very big images for example 10000 x 10000
