### ISSUE TITLE
App does not detect GPU

### ISSUE THREAD

**Issue by Dav-Edward** [Djdefrag/QualityScaler#111]
I recently purchased the app from the Steam Store and found when I try to rescale video the app is always using my CPU instead of my GPU.

GPU utilization during upscaling is always 1%, while all my CPU cores are either busy or near max. I tried setting GPU to Auto and every value with no difference. My system only has a dedicated graphics card.

Specs:
OS - Windows 10, 22H2
Graphics Card - Nvidia GeForce RTX 3060
Graphics Driver - Nvidia 566.14 64-bit
CPU - AMD Ryzen 7 5800X
App run in standard user mode, with administrator ability

Screenshot of Taskmanager while running
![image](https://github.com/user-attachments/assets/12b4a3eb-afab-4349-945a-f5bbbbdb6b68)

**Comment by Djdefrag** [comment]
Hi my friend, 

have you installed this 2 libraries? Typically should already be installed on the pc

1. install Visual-C-Runtimes: 
   - https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

2.  Directx runtime:
   - https://www.microsoft.com/it-it/download/details.aspx?id=35

**Comment by Dav-Edward** [comment]
#Also, for Nvidia GPU Is essential to enable Windows Hardware Accelerated GPU scheduling option
Enable it in Windows 10 / Windows 11 settings > Graphic Settings menu

This I found WAS disabled. Please stand by. Need to restart to test.

**Comment by Djdefrag** [comment]
Let me know my friend, it s a strange situation becuase your pc should be 100% compatible

**Comment by Dav-Edward** [comment]
Bingo, that was it. Night and day difference. Took my 19+ minute job and made it only 40 seconds. That was the problem.
![image](https://github.com/user-attachments/assets/aa5c3d91-d964-40c5-ae09-1d9976cb4592)

For future reference for others, this was 100% the problem:
![image](https://github.com/user-attachments/assets/a7e167cc-1cdb-4019-87aa-3d107e01eb4b)

If Hardware-accelerated GPU scheduling is turned off, the QualityScaler app flat out doesn't utilize the graphics card at all.

Please mark as resolved, unless I can help contribute any additional testing if you'd like. Though could be useful if the app checks for that setting being disabled, or toss that in a FAQ for troubleshooting.

Huge thanks!

**Comment by Djdefrag** [comment]
Perfect! Thank you my friend! 

I imagined that was the problem, because I was able to buy an old Nvidia 1660 and test the app on that and I had noticed this anomaly. (If you see in the next 3.12 changelog I put this in the notes haha)
