### ISSUE TITLE
[BUG] Image output options do nothing

### ISSUE THREAD

**Issue by fueledbyboredom** [Djdefrag/QualityScaler#115]
I'm using the version of the app from itch.io and it appears that the Image output options have zero effect, the extracted and upscaled frames are always jpeg files.

EDIT: Tried on the "Make it work by yourself" version of the app as well and ran into the same issue.

**Comment by fueledbyboredom** [comment]
Sounds good, thanks for cleaning that up for me.

**Comment by Djdefrag** [comment]
You are welcome my friend
