### ISSUE TITLE
Can't get workable .onnx files anywhere

### ISSUE THREAD

**Issue by IvanSCP** [Djdefrag/QualityScaler#116]
### links like https://gofile.io/d/~ doen't work anymore
![Screenshot_20241218_185520_Chrome](https://github.com/user-attachments/assets/929c1568-f3f7-41ef-ac60-62cf2265faf1)

**Comment by Djdefrag** [comment]
Hi my friend, this is the correct link https://gofile.io/d/2RWnDU

**Comment by IvanSCP** [comment]
Thanks. I recommend placing the basic models directly in the source code so that users do not have problems 😅

**Comment by Djdefrag** [comment]
Hi my friend, sadly some models are heavier than 25MB (the limit for github) :(
