### ISSUE TITLE
No load on duplicate extension

### ISSUE THREAD

**Issue by JannickOste** [Djdefrag/QualityScaler#15]
Hi, i was upscaling some assets of a game im converting for a unity project. 
Now when i decompiled the assets the names where: {name}.bmp.png <- this is where the problem is 
When you drag the files into qualityscaler it just gives a gray screen but when changing file names to {name}.png they load normaly? 

Dont know how you extension checking, but assuming from source you use python, could split name on . and do a -1 index to get extension instead. havent checked out the source do, will do when i have a bit more time.

**Comment by Djdefrag** [comment]
Hi, thank you :D
 
yes, actually it counts how many times there are for example .jpg, .png etc in the filename to count files
