### ISSUE TITLE
Loseless output would be nice.

### ISSUE THREAD

**Issue by ythoimust** [Djdefrag/QualityScaler#16]
Output format other than jpeg would be nice. Something loseless like PNG.

**Comment by OoDeeR** [comment]
I second this. Currently, the heavy jpg artifacting makes the result almost entirely unusable. At least having the choice between 1.) quick and dirty jpg and 2.) high quality png would be nice.

**Comment by Djdefrag** [comment]
Thank you! :D 

yes, I'm actually working on the possibility to choose the output format  :)

**Comment by wankio** [comment]
i think png only show different when you zoom 150-200% right?

**Comment by Djdefrag** [comment]
I found that indeed there are quality differences using the .png format, this feature will be introduced in the next release :)
