### ISSUE TITLE
Processing images is way to slow needs to be speed up 

### ISSUE THREAD

**Issue by DJboutit** [Djdefrag/QualityScaler#18]
The time it takes to process images with Qualityscaler is way to long it should not take 10 to 15 min to process any image.  I have tested Quality vs Upscayl with Upscayl most images I can process it 3 or 4 times in the amount of time it takes Quality to process a image once this is the main negative thing about this program please take a look into this thx.  

My video card is a RX 6600 I have 24gb DDR3 settings I use GPU and 6gb to 8gb Vram.  My setup is pretty good for upscaling images.

**Comment by Djdefrag** [comment]
Hi 10/15 minutes is really too much time for a single image; are you sure that your gpu is used? 

The speed really depends on how big is your image; for example in my testing with a GTX 1660 with ~1080P image takes 10 seconds.

What image resolution are you using? Windows 10 or Windows 11?
Try to check if your gpu is used while upscaling in Task Manager.

Thank you for your feedback :)

**Comment by DJboutit** [comment]
I am running 1440p resolution on Windows 10 original image size of the images I start with are like 3000x4000 or 4000x2500

**Comment by Djdefrag** [comment]
Strange. With logic that your rx 6600 is faster than my 1660 so a 3000x4000 should take around ~1 minute in worst case.

Maibe is something related to Pytorch with newer gpus, sadly I can't afford new Gpus to testing :(

In any case try with something <1000x1000 just to test if works correctly :) (Should take ~30 seconds)

**Comment by Djdefrag** [comment]
this is a good time, i will tweak some logic for VRAM limiter, that should be the problem

while you wait for next release, try to set 6GB Vram and try a normal 3000x4000 :)

**Comment by DJboutit** [comment]
Ok thx I will try out the next version

**Comment by Djdefrag** [comment]
Thank you :)
