### ISSUE TITLE
Old Job not cancelling

### ISSUE THREAD

**Issue by kiranmaya2** [Djdefrag/QualityScaler#2]
first, I tried a video, stopped in middle, and next I put an image, yet it resumes old video job.

**Comment by Djdefrag** [comment]
Hi, thank you. I will check ASAP. Can you tell me your pc specs and in which phase did you stopped the video upscaling? 
There are different steps, for example: 
1) Extracting video frames
2) Preparing for upscale
3) Upscaling
4) Upscaled frames n...

Thank you for your support :)
