### ISSUE TITLE
Trojan virus in 4.1 release

### ISSUE THREAD

**Issue by Stl5n0** [Djdefrag/QualityScaler#21]
So um yeah, I love this app but this is concerning. Hopefully its a false positive... Windows 10, downloaded this- [https://github.com/Djdefrag/QualityScaler/releases/download/4.1/QualityScaler_4.1_free.zip](url) version and immediately got that warning when i unzipped it.

![IMG_9135](https://user-images.githubusercontent.com/88563592/198819063-b50a9804-2671-4048-b6a7-73fbda10d6ba.jpg)

**Comment by Djdefrag** [comment]
Hi, thank you :)

Yes, is a known bug caused by the library Pyinstaller used to transform the app from .py to .exe. 
https://www.reddit.com/r/learnpython/comments/sidi10/pyinstaller_exe_is_labeled_as_a_trojan_by_avg/

**Comment by Stl5n0** [comment]
Ahhh ok, thanks! Avast is a pain in the ass sometimes (all the time actually) but thanks for quick reply. I love this app.

**Comment by Djdefrag** [comment]
Thank you :D
