### ISSUE TITLE
Stuck on Preparing

### ISSUE THREAD

**Issue by creativewax** [Djdefrag/QualityScaler#22]
I am processing a 1024x1024 video which is 20mins long, it pre-processed the upscale and then for the last hour+ has been stuck on the message of Preparing for upscaling. When i check Task Manager, the CPU or the GPU is not being used at all, CPU i9 12900f at 15% and GPU RTX 3080 10gb at 1%

am i missing something or do i just have to wait due to the length of the video i am processing?

everything has been left on default settings, BSRGANx4, and 75% with GPU backend

**Comment by Djdefrag** [comment]
Hi, 
in this phase the cpu should be working resizing frames. Actually this is a single-thread task so 15% means that 1 core of your cpu is actually working.

But to be sure of this you can check in QualityScaler folder, there is a directory called QualityScaler_temp, there are stored all frames and resized frames. Can you check please? :)

**Comment by Djdefrag** [comment]
Nice :D 

Sadly qualityscaler is not designed to handle such long videos, but optimization of resize and frame extraction is in pipeline :)

**Comment by Djdefrag** [comment]
Ah I thought about it now, keep an eye on the available space because a 20-minute video, at 30fps = 36000 frames. 
An average frame can weigh as much as 5 Mb so: 
36000 * 5 = 180000 MB ~ 180Gb

**Comment by creativewax** [comment]
Thats fine, its started processing the video, but its still only on 10% CPU and about 6% GPU and not processing very fast

**Comment by Djdefrag** [comment]
Only 6% gpu? But is processing, right?

**Comment by creativewax** [comment]
Yeah its processing, the GPU is rarely getting over 3% usage

**Comment by Djdefrag** [comment]
Are you on Windows 11 22H2? Because it has problems with nvidia gpus and task manager. Do you have other app to check usage? msi afterburner or gpuz for example

**Comment by creativewax** [comment]
Windows 10, i have just opened Armoury Crate and GPU is at 95-100% ha

**Comment by creativewax** [comment]
Good to know, thanks man
