### ISSUE TITLE
Application does not cleanup old files wasting disk space on exit

### ISSUE THREAD

**Issue by lamcjlu** [Djdefrag/QualityScaler#23]
Ran it a few times, job didnt complete cause i ran outnof disk soace. 
Apparently it doesnt clean up old image files extracted from videos? 
would be tood if i could change the cache paths

**Comment by lamcjlu** [comment]
Might be a good idea to allow people to skip the resizing procedure as its slow af as well and not nessesary as they may like to keep the image 100% instead of 75%

**Comment by Djdefrag** [comment]
Hi, actually the "cache folder" cleans everytime starts a new video upscaling.

But i will make it clean when upscale finish, which seems a more correct thing :)

Currently, in addition to resizing the images, qualityscaler prepares them in the best possible way for the passage in the neural network, so it can't skip even putting 100% resize. But i'm also working to make resize faster :)
