### ISSUE TITLE
Error upscaling check log file

### ISSUE THREAD

**Issue by ChrisVRMF** [Djdefrag/QualityScaler#25]
Build version 6.0 Free
After generating images and resizing images. fails to start upscaling.

Error in QualityScaler.log is :
Error while upscaling

CHECK failed: ((((HRESULT)((backend_->dml_device->CreateOperator(&op_desc_, __uuidof(**(&op)), IID_PPV_ARGS_Helper(&op))))) >= 0)) == (true):

**Comment by Djdefrag** [comment]
Hi, did you follower README and installed all necessary?
What are your pc specs? :)

**Comment by Djdefrag** [comment]
Thank you for the precious feedback.

Yes, you did the setup perfectly. This must be a problem with Pytorch-directml library with newer gpus, i hope the will fix this error in next release. I'm sorry I can't help you :(

**Comment by Djdefrag** [comment]
Ah, last thing that you can try is to set GPU preference for QualityScaler in GPU Windows option. 
Your pc has 2 gpus, one dedicated (the 3080) and one with cpu (Intel® UHD Graphics ), you can try to select only 3080 :)

**Comment by ChrisVRMF** [comment]
When I look at the AI Backend. I only have 2 options "GPU and CPU" .

I just tried with CPU setting here and resulted in the same error message as the original post.

**Comment by ChrisVRMF** [comment]
If there is any other information I can provide to help debug I am happy to assist. I have been able to use the software on my other computer with a 2070 Super, and the results are excellent. However its much slower on that computer and would rather run it on my 3080.

**Comment by ChrisVRMF** [comment]
This fixed my problem!!!! Thank you for your help!

**Comment by Djdefrag** [comment]
Nice!! 

I will add this info in README, thank you for trying this :D
