### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ChristianMGr93** [Djdefrag/QualityScaler#28]
The readme file should really include additional instructions for compiling the project from the source code, not just instructions on downloading the .exe and the photo examples. May users will be able to do so from their own knowledge, but others may be new or may be unfamiliar and those additional instructions can be a big help.

**Comment by Djdefrag** [comment]
Hi @ChristianMGr93,
you're right, i will add instructions asap :)

**Comment by pwright225** [comment]
how do i compile and use this? i have been trying and trying and so far no luck.  does anyone know where i can find any information?

**Comment by Djdefrag** [comment]
Hi my friend,

you must have Python 3.10.x installed.

1. Download the project
2. Install all dependencies, you can do it by `pip install -r requirements.txt`
3. Execute QualityScaler.py
