### ISSUE TITLE
Trial Version?

### ISSUE THREAD

**Issue by JPVenson** [Djdefrag/QualityScaler#29]
Hey, i would love to test this upscaler but i was only able to find the paid version with the models. I read in some instances that there is a trial version but could not find it.

**Comment by Djdefrag** [comment]
Hi! 
You can try the script installing:
0. Download the project, and the 3 AI models here: https://drive.google.com/drive/folders/13kfr3qny7S2xwG9h7v95F5mkWs0OmU0D and put them in a directory called "AI"
1. Install Python 3.10
2. Install packages with "pip install -r requirements.txt"
3. execute the script 

:)
