### ISSUE TITLE
Can not drag-and-drop Images to QualityScaler 1.5.0

### ISSUE THREAD

**Issue by DelmorS** [Djdefrag/QualityScaler#3]
After latest update to version 1.5.0 can not drag-and-drop images to QualityScaler. For version 1.4.0 everything worked correctly.
Tried to drop .jpg and .png files - not working.
For videos (tested .mkv) everything works correctly.

I am using Windows 11 64 bit Pro, 22000.652, with clean installation of QualityScaler (from archive from Google Drive)

**Comment by DelmorS** [comment]
> Hi, thank you for your feedback. :) What do you mean drag-and-drop doesn't work? A single image? or multiple images? When you drag-and-drop, does anything appear in the app? Does it go all black? Or does it do nothing?
> 
> Thank you :)

When I drag-and-drop nothing appears in the app, it does nothing.

BUT, In fact I found core reason of the problem:
I had Cyrillic symbols in my path - if you have any, even 1 cyrillic symbol, upon drag-and-drop nothing will happen. If you rename folder/filename back to latin symbols - everything works correctly

**EXAMPLES WITH ERRORS, TO REPRODUCE**
Path or filenames should be following:
D:\Sync\Pictures\ъяю\Test.jpg
D:\Sync\Pictures\TestFolder\ъяю.jpg

**SUCCESSFUL EXAMPLES**
D:\Sync\Pictures\Avatar\TestFolder\Test.jpg
D:\Sync\Pictures\Avatar\TestFolder\AnyOtherName.png

**Comment by Djdefrag** [comment]
Uh perfect, so this is the problem! The app does not digest these symbols.
Really thank you, i will try to resolve integrate support for non-latin pathname strings asap :D 

Really really thank you :)

**Comment by superuser7777** [comment]
Japanese/Kanji similarly fails to drag and drop.

(I use it for upscaling images with text. Thank you for publishing great software!)

**Comment by Djdefrag** [comment]
Thank you :D
