### ISSUE TITLE
Permission denied when I want to drag and drop a file on Windows 10

### ISSUE THREAD

**Issue by zNNiz** [Djdefrag/QualityScaler#31]
OS: WIndows 10
I opened your app, tried to open my photo and this happened to me :(
![annotation](https://user-images.githubusercontent.com/96877065/217356732-d61eaff4-78ce-4f96-9bb5-602e6fa3f3c3.png)

**Comment by Djdefrag** [comment]
Hi my friend,
it seems you don't have permission to write in the script directory, you can try to execute the script as Administrator or give some permission to the folder :)

**Comment by Djdefrag** [comment]
Did you tried to set folder permission? Or changing path? Maibe put the directory on Desktop :)

**Comment by Derjyn** [comment]
Running as admin. Folder permissions are totally open. Drag and drop simply doesn't work. Your paid version on itch.io works. Seems a little... odd.

**Comment by Djdefrag** [comment]
This is strange, did you installed all packages in requirements.txt?

In any case, this drag&drop problem will be resolved in version 2.0. It has always been problematic to get it working properly, and also, working on a new gui with other libraries, the drag&drop widget is not compatible. 

Sorry about the problem.

**Comment by Djdefrag** [comment]
@zNNiz Ah, i saw this right now! Are you using python installed by Microsoft Store? Because it is super problematic, try to install it by the official Python release on the website, but first uninstall Microsoft Store version.

 Maibe this will resolve the issue
