### ISSUE TITLE
Error while upscaling  'utf-8' codec can't decode byte 0xf3 in position 1670: invalid continuation byte

### ISSUE THREAD

**Issue by fe80Grau** [Djdefrag/QualityScaler#32]
Hi,
in windows 11, 
Error otuput when click in upscale button.
```
Error while upscaling

'utf-8' codec can't decode byte 0xf3 in position 1670: invalid continuation byte
```
![image](https://user-images.githubusercontent.com/6680464/221377394-594baec9-4f0b-4e11-bba3-db4d4862e266.png)

file path: C:\Users\Usuario\OneDrive\Documentos\github\RealScaler\Bleach.avi

My windows system uses spanish language but the path doesn't contain special chars. i can't trace this because otuput error is not showing the complete error.

**Comment by Djdefrag** [comment]
Hi my friend,

the file is a OneDrive file? try to download it locally :)
