### ISSUE TITLE
how run in linux, no gui，thanks

### ISSUE THREAD

**Issue by hktalent** [Djdefrag/QualityScaler#34]
how run in linux, no gui，thanks

**Comment by Djdefrag** [comment]
Hi, 

actually the app uses Pytorch-directml which is strictly for windows. 

If you want to use it on linux, especially with Nvidia gpus (cuda) you should:
- refer to Pytorch page https://pytorch.org/get-started/locally/ to install torch with cuda
- replace all occurrences of _.to(backend)_ with _.("cuda")_

and it should work. 

PS. do not forget to download the pretrained AI models from here: https://github.com/cszn/BSRGAN

**Comment by hktalent** [comment]
It would be great if there is a version running here, thank you very much
https://colab.research.google.com
