### ISSUE TITLE
BSRGAN 2X not available?

### ISSUE THREAD

**Issue by Stl5n0** [Djdefrag/QualityScaler#38]
2.2 had no option for the 2x BSRGAN model, and if memory serves, it’s been available up until now. Haven’t checked 2.3 yet but I didn’t see the model in the Folder zip when I downloaded it from the purchase page. 

Not a huge issue, but I’ve found that most videos come out much better when upscaling double as opposed to quadruple res. Thanks, and keep up the amazing work 🙏🏻

**Comment by Djdefrag** [comment]
Hello my friend, 

the x2 model was temporarily because it was causing problems with the latest version of torch-directml. 
I will reintegrate it as soon as the library fixes the problem with the model :)
