### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Joly0** [Djdefrag/QualityScaler#4]
Hey, this project looks interesting and works good on windows, though it would be great, if this could be used on linux aswell. A great usecase for this would be inside a docker container which one can access through vnc or similar. This could aswell be run on a small Linux server ( with a nvidia gpu for cuda), rather than the main machine, without consuming storage and cpu/gpu resources, leaving the main system free for different work (as the process can take quite long for larger files)

**Comment by Djdefrag** [comment]
Hi, thank you :D 

Yes, the project can evolve in many ways, i choosed Windows just because with Pytorch-directml in version 2.0.0 just released it is now compatible with all Gpus :)

**Comment by Joly0** [comment]
Thanks for your reply, but isnt it possible to adjust it, so it could work in linux? Linux (and even docker containers) can use gpu´s and pytorch-directml is, as far as i can see, is available for linux aswell

**Comment by Joly0** [comment]
Btw, a simple py script that could use some arguments, without the gui, would be suitible for use in linux, so in my opinion, there is no need for a gui in linux, which maybe might make it simpler?

**Comment by Djdefrag** [comment]
yes, of course :D

**Comment by faveoled** [comment]
![image](https://user-images.githubusercontent.com/85760289/172012948-da3ba46d-bc78-4209-8368-89a0c47c9949.png)
@Joly0 GUI works on Linux with minor changes to code. It's likely Pytorch-directml should be replaced by torch on Linux. There are also some windll dependencies that are a problem. Upscaling itself fails for me though.

**Comment by Djdefrag** [comment]
Wow! Thank you @faveoled! Can you share some info how did you do it? 
Wine maibe? :D

In version 1.5 i was using Pytorch + cuda, so something can be found there; in fact it only needs to change the code from ".to("dml")" in ".to("cuda")"

**Comment by faveoled** [comment]
@Djdefrag No wine. Tkinter is cross platform, no issue here. Just installed necessary packages and commented out windll calls.

**Comment by Djdefrag** [comment]
Perfect, maybe i can integrate a if statement for windll calls only if os is Windows, thank you :D

**Comment by Joly0** [comment]
Anything new about this?

**Comment by l3td33r** [comment]
I'm interested in this as well!
I tried running on linux with wine, but it doesn't work at all. I would really like to use this app and can't right now!

**Comment by Joly0** [comment]
@Djdefrag Any progress on this one? It would be super usefull, if this could be run on linux

**Comment by Djdefrag** [comment]
HI @Joly0, no news about this sorry. I recently changed jobs and can't devote much time to these side projects. 

To make it work there are two things to do on linux:
1. Change from pytorch-directml to pytorch (will work only on nvidia cards and cpu)
2. Change input filepaths, for example change the "/" in the paths with os.sep() 

I think that all need to make it run on linux. I m really sorry i can't work to the project

**Comment by Joly0** [comment]
Hey, did anything change regarding linux support? I would really appreciate to have this to work in linux

**Comment by l3td33r** [comment]
Samee

**Comment by faveoled** [comment]
I found a similar project called Upscayl: 
https://github.com/upscayl/upscayl
Works for me on Linux.

**Comment by Djdefrag** [comment]
Hi :D,

sadly no news about linux version. The pytorch library used is specifically for Windows to be able to use AI on any gpus :(

**Comment by Joly0** [comment]
> I've found a similar project called Upscayl: https://github.com/upscayl/upscayl Works for me on Linux.

I tinkered quite alot with it for docker, but i didnt get it to work, so it isnt really a proper alterantive

**Comment by ChristianMGr93** [comment]
Alongside Linux support, at least some CLI support for macOS would be welcome, as well, especially with the newer m-series chips being leveraged effectively for AI processing. There may be some success attempting to push the program as a .exe through WINE but it would be nice to avoid any potential failure points or inefficiencies resulting from that.

**Comment by Djdefrag** [comment]
Hi @ChristianMGr93,

pytorch-directml, the library used to execute the AI is only compatible with Windows because it uses Directx12 API.

This means that a macOS port is not possible, but I'm working for a Linux port via some sort of translation from Directx12 to Vulkan but with no success at the moment :(
