### ISSUE TITLE
Not full loaded GPU Only 50%

### ISSUE THREAD

**Issue by Kittyskj** [Djdefrag/QualityScaler#45]
Videocard Rtx 2060 12gb vram. Driver 545.84 driver game ready windows 11, python 3.10.6 
Program or model idk not full use vram
![image](https://github.com/Djdefrag/QualityScaler/assets/73357005/eec871ec-722d-456b-95d1-a9d33ba2a1d0)

**Comment by Djdefrag** [comment]
Hi my friend, 

it is normal, RealESR_G is a "small and light" AI model and use low resources :)

if you select BSRGANx4 you can see all your VRAM full for example

**Comment by Kittyskj** [comment]
> Hi my friend,
> 
> it is normal, RealESR_G is a "small and light" AI model and use low resources :)
> 
> if you select BSRGANx4 you can see all your VRAM full for example

Thx for help

**Comment by Kittyskj** [comment]
Answerd
