### ISSUE TITLE
Error during upscaling of single-bit-depth black & white png

### ISSUE THREAD

**Issue by Somdudewillson** [Djdefrag/QualityScaler#46]
The upscale process is failing on a particular image with the error "not enough values to unpack (expected 3, got 2)". The image in question is a black & white PNG with a bit depth of 1.

**Comment by Djdefrag** [comment]
Hi my friend, can you share the image so I can reproduce the error please? :)

**Comment by Somdudewillson** [comment]
Ah, should have thought of that myself - here you go:
<img width="270" alt="e892398021f55b7073e195e689818398" src="https://github.com/Djdefrag/QualityScaler/assets/11532319/4c09bd14-ae1e-4334-b7ff-5562105db1f8">

**Comment by Djdefrag** [comment]
Thank you my friend, 

i will fix in next release :)
