### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by WindowsNT** [Djdefrag/QualityScaler#55]
It would help if this could be installed via pip.
I'm still trying to install the dependencies and I eventually get

```
Traceback (most recent call last):
  File "QualityScaler.py", line 617, in <module>
    ) -> list[numpy_ndarray]:
TypeError: 'type' object is not subscriptable
```

**Comment by Djdefrag** [comment]
Hi my friend,

you have to install dependencies written in requirements.txt.

You can do it automatically with:

> pip install -r path_to_the_file/requirements.txt

Make sure you have python <= 3.10.x because currently python 3.11.x is not supported by some dependencies

**Comment by WindowsNT** [comment]
Thanks for your help, still.

```
Traceback (most recent call last):
  File "QualityScaler\QualityScaler.py", line 617, in <module>
    ) -> list[numpy_ndarray]:
TypeError: 'type' object is not subscriptable
```

when trying with Python 3.8.

**Comment by Djdefrag** [comment]
Mmh try to use Python 3.10.x, never tested on previous Python version

**Comment by WindowsNT** [comment]
With 3.10.11 I get 

F:\python>scripts\pip install -r qualityscaler\requirements.txt
ERROR: Could not find a version that satisfies the requirement torch-directml==0.1.13.1.dev230413 (from versions: none)
ERROR: No matching distribution found for torch-directml==0.1.13.1.dev230413

What's the exact version you are using?

**Comment by Djdefrag** [comment]
This is the exact version i am using, are you sure you are in python 3.10 context? Have you unistalled 3.8?

**Comment by WindowsNT** [comment]
Yes. 
F:\python>python -V
Python 3.10.11
But I'm using a portable Python install, perhaps you have something I don't have.

**Comment by Djdefrag** [comment]
I think that python must be installed native

**Comment by WindowsNT** [comment]
Okay I will see what I can do, my goal is to include QualityScaler in my video sequencer in which all Python-based modules are separately downloaded and installed for the user's convenience.

**Comment by Djdefrag** [comment]
okk, let me know if it works :)

**Comment by przvlprd** [comment]
Ran into the same problem. I used conda to solve it and it only worked on Python 3.10.

```
cd QualityScaler
conda create -n qualityscaler python=3.10 pip
conda activate qualityscaler
pip install -r requirements.txt
```
