### ISSUE TITLE
cannont run QualityScaler.py with python 3.10.11

### ISSUE THREAD

**Issue by pwright225** [Djdefrag/QualityScaler#59]
i can't figure out how to use this.

python.exe -V
Python 3.10.11

pip install -r requirements.txt
Collecting torch-directml==0.1.13.1.dev230413 (from -r requirements.txt (line 2))
  Downloading torch_directml-0.1.13.1.dev230413-cp310-cp310-win_amd64.whl (8.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 11.4 MB/s eta 0:00:00
Collecting customtkinter (from -r requirements.txt (line 5))
  Downloading customtkinter-5.2.1-py3-none-any.whl.metadata (652 bytes)
Collecting packaging (from -r requirements.txt (line 6))
  Downloading packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting moviepy (from -r requirements.txt (line 9))
  Downloading moviepy-1.0.3.tar.gz (388 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 388.3/388.3 kB 12.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting opencv-python-headless (from -r requirements.txt (line 10))
  Downloading opencv_python_headless-4.9.0.80-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting nuitka (from -r requirements.txt (line 11))
  Downloading Nuitka-1.9.6.tar.gz (3.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 13.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting torch==1.13.1 (from torch-directml==0.1.13.1.dev230413->-r requirements.txt (line 2))
  Downloading torch-1.13.1-cp310-cp310-win_amd64.whl (162.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.6/162.6 MB 5.2 MB/s eta 0:00:00
Collecting torchvision==0.14.1 (from torch-directml==0.1.13.1.dev230413->-r requirements.txt (line 2))
  Downloading torchvision-0.14.1-cp310-cp310-win_amd64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 13.9 MB/s eta 0:00:00
Collecting typing-extensions (from torch==1.13.1->torch-directml==0.1.13.1.dev230413->-r requirements.txt (line 2))
  Downloading typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
Collecting numpy (from torchvision==0.14.1->torch-directml==0.1.13.1.dev230413->-r requirements.txt (line 2))
  Downloading numpy-1.26.2-cp310-cp310-win_amd64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 3.2 MB/s eta 0:00:00
Collecting requests (from torchvision==0.14.1->torch-directml==0.1.13.1.dev230413->-r requirements.txt (line 2))
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision==0.14.1->torch-directml==0.1.13.1.dev230413->-r requirements.txt (line 2))
  Downloading pillow-10.2.0-cp310-cp310-win_amd64.whl.metadata (9.9 kB)
Collecting darkdetect (from customtkinter->-r requirements.txt (line 5))
  Downloading darkdetect-0.8.0-py3-none-any.whl (9.0 kB)
Collecting decorator<5.0,>=4.0.2 (from moviepy->-r requirements.txt (line 9))
  Downloading decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting tqdm<5.0,>=4.11.2 (from moviepy->-r requirements.txt (line 9))
  Downloading tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 3.2 MB/s eta 0:00:00
Collecting proglog<=1.0.0 (from moviepy->-r requirements.txt (line 9))
  Downloading proglog-0.1.10-py3-none-any.whl (6.1 kB)
Collecting imageio<3.0,>=2.5 (from moviepy->-r requirements.txt (line 9))
  Downloading imageio-2.33.1-py3-none-any.whl.metadata (4.9 kB)
Collecting imageio_ffmpeg>=0.2.0 (from moviepy->-r requirements.txt (line 9))
  Downloading imageio_ffmpeg-0.4.9-py3-none-win_amd64.whl.metadata (1.7 kB)
Collecting ordered-set>=4.1.0 (from nuitka->-r requirements.txt (line 11))
  Downloading ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Collecting zstandard>=0.15 (from nuitka->-r requirements.txt (line 11))
  Downloading zstandard-0.22.0-cp310-cp310-win_amd64.whl.metadata (3.0 kB)
Requirement already satisfied: setuptools in c:\programdata\miniconda3\envs\qualityscaler\lib\site-packages (from imageio_ffmpeg>=0.2.0->moviepy->-r requirements.txt (line 9)) (68.2.2)
Collecting charset-normalizer<4,>=2 (from requests->torchvision==0.14.1->torch-directml==0.1.13.1.dev230413->-r requirements.txt (line 2))
  Downloading charset_normalizer-3.3.2-cp310-cp310-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests->torchvision==0.14.1->torch-directml==0.1.13.1.dev230413->-r requirements.txt (line 2))
  Downloading idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests->torchvision==0.14.1->torch-directml==0.1.13.1.dev230413->-r requirements.txt (line 2))
  Downloading urllib3-2.1.0-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests->torchvision==0.14.1->torch-directml==0.1.13.1.dev230413->-r requirements.txt (line 2))
  Downloading certifi-2023.11.17-py3-none-any.whl.metadata (2.2 kB)
Collecting colorama (from tqdm<5.0,>=4.11.2->moviepy->-r requirements.txt (line 9))
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading customtkinter-5.2.1-py3-none-any.whl (295 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.0/296.0 kB 17.9 MB/s eta 0:00:00
Downloading packaging-23.2-py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 2.7 MB/s eta 0:00:00
Downloading opencv_python_headless-4.9.0.80-cp37-abi3-win_amd64.whl (38.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.5/38.5 MB 11.1 MB/s eta 0:00:00
Downloading imageio-2.33.1-py3-none-any.whl (313 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 313.3/313.3 kB 9.8 MB/s eta 0:00:00
Downloading imageio_ffmpeg-0.4.9-py3-none-win_amd64.whl (22.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.6/22.6 MB 12.6 MB/s eta 0:00:00
Downloading numpy-1.26.2-cp310-cp310-win_amd64.whl (15.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.8/15.8 MB 13.1 MB/s eta 0:00:00
Downloading requests-2.31.0-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB ? eta 0:00:00
Downloading tqdm-4.66.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB ? eta 0:00:00
Downloading zstandard-0.22.0-cp310-cp310-win_amd64.whl (511 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.6/511.6 kB 10.7 MB/s eta 0:00:00
Downloading certifi-2023.11.17-py3-none-any.whl (162 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.5/162.5 kB 9.5 MB/s eta 0:00:00
Downloading charset_normalizer-3.3.2-cp310-cp310-win_amd64.whl (100 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.3/100.3 kB 6.0 MB/s eta 0:00:00
Downloading idna-3.6-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 3.2 MB/s eta 0:00:00
Downloading pillow-10.2.0-cp310-cp310-win_amd64.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 11.1 MB/s eta 0:00:00
Downloading urllib3-2.1.0-py3-none-any.whl (104 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.6/104.6 kB ? eta 0:00:00
Downloading typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Building wheels for collected packages: moviepy, nuitka
  Building wheel for moviepy (setup.py) ... done
  Created wheel for moviepy: filename=moviepy-1.0.3-py3-none-any.whl size=110765 sha256=fbdcc36b5789a22c71e43b57f74917ca03d58509ecb8cea3ae3ae461805f089e
  Stored in directory: c:\users\administrator\appdata\local\pip\cache\wheels\96\32\2d\e10123bd88fbfc02fed53cc18c80a171d3c87479ed845fa7c1
  Building wheel for nuitka (pyproject.toml) ... done
  Created wheel for nuitka: filename=Nuitka-1.9.6-cp310-cp310-win_amd64.whl size=3244461 sha256=f1d0f72762d10272b93b19d8c96697cfd6b25e753d3c1eb6bec7c9959ddb3c61
  Stored in directory: c:\users\administrator\appdata\local\pip\cache\wheels\f5\aa\20\4a4b02c5a4115b3f674a2540a48105f39d491501d2fe68fee8
Successfully built moviepy nuitka
Installing collected packages: zstandard, urllib3, typing-extensions, pillow, packaging, ordered-set, numpy, imageio_ffmpeg, idna, decorator, darkdetect, colorama, charset-normalizer, certifi, tqdm, torch, requests, opencv-python-headless, nuitka, imageio, customtkinter, torchvision, proglog, torch-directml, moviepy
Successfully installed certifi-2023.11.17 charset-normalizer-3.3.2 colorama-0.4.6 customtkinter-5.2.1 darkdetect-0.8.0 decorator-4.4.2 idna-3.6 imageio-2.33.1 imageio_ffmpeg-0.4.9 moviepy-1.0.3 nuitka-1.9.6 numpy-1.26.2 opencv-python-headless-4.9.0.80 ordered-set-4.1.0 packaging-23.2 pillow-10.2.0 proglog-0.1.10 requests-2.31.0 torch-1.13.1 torch-directml-0.1.13.1.dev230413 torchvision-0.14.1 tqdm-4.66.1 typing-extensions-4.9.0 urllib3-2.1.0 zstandard-0.22.0

**from the anaconda prompt**
(qualityscaler) C:\Users\Administrator\Git\QualityScaler>C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe QualityScaler.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Git\QualityScaler\QualityScaler.py", line 35, in <module>
    from PIL.Image        import open as pillow_image_open
ModuleNotFoundError: No module named 'PIL'

**from the 'normal' windows terminal**
C:\Users\Administrator\Git\QualityScaler>C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe QualityScaler.py
Access is denied.

**Comment by Djdefrag** [comment]
Mh you are using a anaconda environment?
It says that a package called Pillow can t be found, you can install with `pip install pillow`

Never tried a portable environment, can you try to install Python native on Windows?

**Comment by pwright225** [comment]
i will uninstall mh cause i only had it due to the many many many things i was trying to get it to work. when i couldn't get 'conda' to work.

i have since uninstalled all other version of python and only have a non-portable version of python 3.10.11 only

**Comment by Djdefrag** [comment]
okk

**Comment by pwright225** [comment]
IT WORKS!  thank you so much.

i had to fully uninstall anything to do with python including notepad++ python script and the python 3.11.10 i am using  and rebooted between each.  then reinstalled it. then reinstalled the requirements .. this time all went in including pillow

is there a place to find a brief summary/ comparison between the different AI models? which is best for what or  just the best?
also of all of your brilliant programs (Quality/Real/Nice) which is best for what or which is best?

**Comment by Djdefrag** [comment]
Nice!!

There is a little "?" near each option that describe anything. If you click on " ? AI Models" there is a little explanation of each model :)

NiceScaler is an old (now abandoned) project based entirely on OpenCV, using very old (~2017) AI models that do not give very good results.

RealScaler is a rib of QualityScaler.
QualityScaler is the main project and contains and will contain all the best AI models I can implement, while RealScaler is a project dedicated only to https://github.com/xinntao/Real-ESRGAN.

Initially it was supposed to be a single project, but in the beginning with all the models the project weighed more than 4GB, too much to load the project on any platform. However, in the development stages I managed to lighten it up, but by then I had created two separate projects and left them like this

**Comment by pwright225** [comment]
keep getting errors, i keep reducing the settings and trying again.  does this error mean anything to you?

![image](https://github.com/Djdefrag/QualityScaler/assets/50409761/f79592e6-bb7f-400f-9cad-cdfeee1eac92)

current settings are.

![image](https://github.com/Djdefrag/QualityScaler/assets/50409761/7f365020-f8d0-4c03-a4ef-6cf44ca7e726)


its for a bad made for tv movie that my friends wife is in.  wanted to bump up the quality for them.

**Comment by pwright225** [comment]
you know what it was probably a space issue on the drive. ill am trying to free up space but i have also reduced to 70 on the imput res.  sorry for being such a bother today and thank you for all of you help. 

so quick too.

**Comment by Djdefrag** [comment]
Hi my friend, 

are you trying to upscale a long video? Probably the app can t extract all video frames, keep in mind that each video frame can weight **up to 5 MB**, so it can full your disk :)

**Comment by pwright225** [comment]
im on 'Processing upscaled video' for a long while now. is there a log or anything i can monitor?
