### ISSUE TITLE
image files changed & unchanged?

### ISSUE THREAD

**Issue by Hifilo** [Djdefrag/QualityScaler#60]
Hi, perhaps this is a bug,

I tried upscaling a few images and noticed sometimes I will get 

```Loading
Loading AI model
1. Upscaling image
    0 image files updated
    1 image files unchanged
2. Upscaling image
    0 image files updated
    1 image files unchanged
3. Upscaling image
    0 image files updated
    1 image files unchanged
Completed
> Uploaded files: 1 => Supported files: 1
```

however in explorer, there are new files, and with larger dimensions, and larger file size:

![explorer_9aMewWxQpd](https://github.com/Djdefrag/QualityScaler/assets/92943726/40fb96c8-49a6-482d-af2c-8b431b1236c7)

Perhaps I need to update the models, or it requires active internet connection to use?

**Comment by Djdefrag** [comment]
Hi my friend,

these 2 logs are from exiftool when copying the metadata of the original image to the upscaled image

do not affect the upscale phase :)

```
0 image files updated
1 image files unchanged
```

**Comment by Hifilo** [comment]
okay great. I was worried it was increasing the size & dimensions, but the upscale process failed. Thank you!
