### ISSUE TITLE
improvement: add upscale resolution to the UI list

### ISSUE THREAD

**Issue by Hifilo** [Djdefrag/QualityScaler#61]
Hello, 

After using this a few times I feel that adding a column in the UI to show the up-scaled dimensions before proceeding with the process would be beneficial.

This way you can gauge what resolution to use to reach your target resolution.

Otherwise this is a great tool!

**Comment by BobHasNoSoul** [comment]
i agree this would be a good addition, right now i am using the input resolution and maths to work out the output resolution.. i mean you get the resolution but its extra work that way

**Comment by Djdefrag** [comment]
Thank you! Absolutely, i will add this function in next release :)
