### ISSUE TITLE
Models won't load

### ISSUE THREAD

**Issue by opticblu** [Djdefrag/QualityScaler#66]
The path appears to be incorrect:

Error[Errno 2] No such file or directory: 'I:\\videoup\\QualityScaler\\AI-onnx\\RealESR_Gx4.onnx'

Latest release, tried in python 3.10 and 3.11, in conda env and outside of env

Please advise

Thank you!

**Comment by Djdefrag** [comment]
Hi my friend, 

I am trying to upload the onnx models and also the script to convert the torch models to onnx models :)

**Comment by Djdefrag** [comment]
Hi my friend,

just uploaded the link to download the new AI .onnx models (by Gofile) because Github has 25MB file limit :(

**Comment by canDry** [comment]
TLDR: https://gofile.io/d/LXDtm3

**Comment by opticblu** [comment]
Thank you both

**Comment by Aptronymist** [comment]
You do understand that it would be trivial to just upload all of those models to huggingface and have them automatically download with their hub tools, right?

**Comment by FurkanGozukara** [comment]
> You do understand that it would be trivial to just upload all of those models to huggingface and have them automatically download with their hub tools, right?

I plan to make this in my auto installer where is the original model links?

**Comment by FurkanGozukara** [comment]
> Hi my friend,
> 
> just uploaded the link to download the new AI .onnx models (by Gofile) because Github has 25MB file limit :(

where are the links? i would like to download all

**Comment by Aptronymist** [comment]
> > You do understand that it would be trivial to just upload all of those models to huggingface and have them automatically download with their hub tools, right?
> 
> I plan to make this in my auto installer where is the original model links?

https://openmodeldb.info is the best source I know of.
