### ISSUE TITLE
GPU not involved during processing (Update: worked using python 3.11.4 as of 20240318)

### ISSUE THREAD

**Issue by darrenqiao** [Djdefrag/QualityScaler#69]
Hi, 
I tried to upsacler a sample video and checked the GPU/CPU status. Only CPU and memory works hard during process.
![image](https://github.com/Djdefrag/QualityScaler/assets/32362288/178ad12f-9c57-46ba-8997-be5e9feaa05b)

Is there anything wrong or is there any specific configuration needed for GPU to join the party?
Thanks.

**Comment by SandwichIsGreat** [comment]
What version of python are you using? I had the same issue and it turned out my python version was not the correct one.

**Comment by darrenqiao** [comment]
> What version of python are you using? I had the same issue and it turned out my python version was not the correct one.

I am using Python 3.10.0. Which version are using?

**Comment by SandwichIsGreat** [comment]
3.11.4 I think. The issue occurred on python 3.10 for me

**Comment by darrenqiao** [comment]
> 3.11.4 I think. The issue occurred on python 3.10 for me

Got it. Will try the version and see if it works. Thanks @SandwichIsGreat

**Comment by darrenqiao** [comment]
@SandwichIsGreat It worked with version 3.11.4. Thanks for the help.
