### ISSUE TITLE
Upscaling separately with tile upscaling causes cuts on upscaled image

### ISSUE THREAD

**Issue by TYX7601** [Djdefrag/QualityScaler#7]
Hi, I just wanted to leave an issue with the upscaling method. I'm not sure if this is RealSR or BSRGAN's issue, but I don't think it is as it happens on both of these. I've basically noticed some cuts on the final image that it creates in the end as it combines the tiles together back into one image.

I suspect this is because for each tile both of these don't give out the upscaled image in the same way as every other tile it upscales. I also don't notice it easily if I view it from about the original scale, but it starts becoming noticeable when I zoom into the image.

The original image:
![modern-house-1-1538579609](https://user-images.githubusercontent.com/49084709/175314393-61c34ae2-c25d-49d5-a4b2-0c36768cee6c.png)

Upscaled using BSRGAN in 4x:
![modern-house-1-1538579609_BSRGAN_x4](https://user-images.githubusercontent.com/49084709/175314407-5028f465-6be0-4268-b7e6-a3161e965c34.png)

Upscaled using RealSR_JPEG in 4x:
![modern-house-1-1538579609_RealSR_JPEG_x4](https://user-images.githubusercontent.com/49084709/175314411-d42eadaa-f461-4720-9457-d10a022e6a21.png)

I also tested this with 2x, and it does the same.
Still, many thanks for making this program!

**Comment by Raz2481** [comment]
I didn't point out the cut areas. I'll show them here.

This is with BSRGAN but it's also there with RealSR.

![highlighted cuts](https://user-images.githubusercontent.com/49084709/175316147-779ee2dc-c9d2-462f-bbcd-29632b46a280.png)

**Comment by Djdefrag** [comment]
Hi, thank you for the feedback.

Yes, it is a known problem caused by tiles/merge function.
To mitigate this problem you can try to:

- use the Fused model 
- set VRAM-RAM option to max 
- or choose other upscale option (x2, x3) instead of x4 

Again, thank you for the feedback  :D

**Comment by Djdefrag** [comment]
Ah, i just released a new update, version 2.2.0, try it if you want :)

**Comment by TYX7601** [comment]
Thank you! I noticed it's been fixed when I tried the same image.

**Comment by Djdefrag** [comment]
Perfect!

Thank you :D
