### ISSUE TITLE
Where are the model download links?

### ISSUE THREAD

**Issue by FurkanGozukara** [Djdefrag/QualityScaler#74]
e.g. : RealESR_Gx4.onnx
Can you point me all models download links?

**Comment by Djdefrag** [comment]
Hi my friend, here is the link 
* https://gofile.io/d/4Dpnls

extract theese file in AI-onnx directory :)

**Comment by dybilisim** [comment]
hello it seems that the link is broken

**Comment by Djdefrag** [comment]
> hello it seems that the link is broken

Hi @dybilisim, the link https://gofile.io/d/hIOmMc seems working.

The link is updated with each release, it is in the AI-onnx folder

**Comment by martianalgos** [comment]
Hello @Djdefrag, can you update link?

**Comment by martianalgos** [comment]
Thx @Djdefrag for rapid response. I tested an app with different settings. I discovered that main source of error is tiling(gpu memory size option). If I choose a 2-3GB all works. Additionally, I was not able to use any other upscaler from list except RealESR_Gx4_fp16. For image upscale, I usually use realesr-general-x4v3.pth that is match faster than others. Should I use onnxconverter for that porposes?

**Comment by danielmwhiley-source** [comment]
Hi @Djdefrag looks like the link is down unless I'm in the wrong place?

**Comment by Djdefrag** [comment]
> Hi [@Djdefrag](https://github.com/Djdefrag) looks like the link is down unless I'm in the wrong place?

Hi my friend, the latest link is this one https://gofile.io/d/b4Ds9u as written in https://github.com/Djdefrag/QualityScaler#make-it-work-by-yourself-%E2%80%8D

Can you access this link?

**Comment by danielmwhiley-source** [comment]
Legend. Thank you
