### ISSUE TITLE
Stucked on Processing upscaled video

### ISSUE THREAD

**Issue by Kolouch-Dominik** [Djdefrag/QualityScaler#75]
Hi, I'm stuck on "Processing upscaled video" for about an hour. It would be nice to see some progress on processing.
Or is this a bug?
![obrázek_2024-05-04_210726612](https://github.com/Djdefrag/QualityScaler/assets/114079305/b75a2efd-733f-4552-a97a-d7ae204d663d)

AMD 7950x3D
Nvidia 4090

**Comment by Djdefrag** [comment]
Hi my friend,

i think there is an error with ffmpeg. The default ffmpeg is the version 4.2 that is not compatible with cpus with >= 16 threads.

To solve this issue you can 2 things:

1. Select in "CPU number" widget any value lower than 16

OR

1. Download the new version of ffmpeg (https://www.gyan.dev/ffmpeg/builds/)
2. Rename "ffmpeg.exe" as "ffmpeg_7.exe" 
3. Put this file in "Assets" directory

**Comment by will-scc** [comment]
I have this same problem with version 3.7 and the following settings:
![image](https://github.com/user-attachments/assets/0546f15a-3296-4e1c-97fe-ddecac5a4c3d)
So not sure it's related to >=16 threads.

**Comment by Djdefrag** [comment]
Hi my friend,

did you build QualityScaler from code? or did you download the version from itch or steam?

If you downloaded the version from code, you should also add the updated version of ffmpeg to the “Assets” folder:

1. download it from here https://www.gyan.dev/ffmpeg/builds/

![Immagine 2024-07-22 122506](https://github.com/user-attachments/assets/79426628-db7c-4af4-9b64-accbade9fdb1)

2. Extract the ffmpeg.exe file from the folder and put it in the “Assets” folder




Because the default version of ffmpeg is very old and may have problems with many modern cpu's. And I can't put the updated version because it is too heavy for github :(

**Comment by will-scc** [comment]
> Hi my friend,
> 
> did you build QualityScaler from code? or did you download the version from itch or steam?
> 
> If you downloaded the version from code, you should also add the updated version of ffmpeg to the “Assets” folder:
> 
>     1. download it from here https://www.gyan.dev/ffmpeg/builds/
> 
> 
> ![Immagine 2024-07-22 122506](https://private-user-images.githubusercontent.com/32263112/350930508-79426628-db7c-4af4-9b64-accbade9fdb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDUzNzQsIm5iZiI6MTcyMTY0NTA3NCwicGF0aCI6Ii8zMjI2MzExMi8zNTA5MzA1MDgtNzk0MjY2MjgtZGI3Yy00YWY0LTliNjQtYWNjYmFkZTlmZGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDEwNDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkYjEzOGZjMTJlZTU2NzFmNGQ4YjJiYjliYTA0MmI4NmQ4MjFmNTE0MGUwZGRmMmM0NTgyNGVmYzM5ZDdkNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sZ3VRbcE23USnHlryaPCw5VBanq01lOW8wzOc-RCyEE)
> 
>     2. Extract the ffmpeg.exe file from the folder and put it in the “Assets” folder
> 
> 
> Because the default version of ffmpeg is very old and may have problems with many modern cpu's. And I can't put the updated version because it is too heavy for github :(

Hi,

I downloaded the `zip` file from the latest release (https://github.com/Djdefrag/QualityScaler/releases/tag/3.7) however I realised that this does not include ffmpeg.exe in the Assets folder.

**It would be very helpful if this was mentioned somewhere in the instructions** (https://github.com/Djdefrag/QualityScaler?tab=readme-ov-file#make-it-work-by-yourself-) as I had no idea this was missing until I checked after reading this issue.

However, even after putting the latest version of `ffmpeg.exe` in the directory it still got stuck on the `Processing upscaled video` step.

**Comment by will-scc** [comment]
> Hi my friend,
> 
> actually QualityScaler comes with ffmpeg 4.2 installed when you download all dependecies, you just updated the ffmpeg version.
> 
> it doesn't tell you anything in the terminal? no errors? if you open task manager do you see the ffmpeg.exe process working?

Hi,

The zip file under Releases does not come with ffmpeg installed. Here is the zip folder:
![image](https://github.com/user-attachments/assets/1e21fa22-74c4-4ab0-b6e7-92434039178d)
As you can see, ffmpeg.exe does not exist there.

However, I realised this and I have now put the latest version of ffmpeg in the Assets folder:
![image](https://github.com/user-attachments/assets/293e39e6-a79e-444c-9dd4-436fd0c8e8d0)

It still gets hung up on `Processing upscaled video`:
![image](https://github.com/user-attachments/assets/b1954360-0591-425f-b8ec-aade32f28984)

**Comment by Djdefrag** [comment]
Yes, app requires reboot to resume the position of ffmpeg.
