### ISSUE TITLE
This verion of exiftool is not compatible

### ISSUE THREAD

**Issue by Maverynthia** [Djdefrag/QualityScaler#77]
`This version of C:\Python3\QualityScaler\Assets\exiftool.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.`

I'm running Windows 10

Is this needed for anything major?

**Comment by Djdefrag** [comment]
Hi my friend, 

Exiftool is used only for copy details of the original file to upscaled file (for example colore profile)

In any case, that is a strange error, are you running a old version of Windows 10?

**Comment by gjnave** [comment]
I got the same error and am running Windows 11 Pro

**Comment by pinea00** [comment]
I am too,win10 22H2

**Comment by Djdefrag** [comment]
@Maverynthia @gjnave @pinea00 

Hi

 - download  Windows executable exiftool.exe from here (https://exiftool.org/)
 - place exiftool.exe in Assets directory

**Comment by pinea00** [comment]
> @Maverynthia @gjnave @pinea00
> 
> Hi
> 
> * download  Windows executable exiftool.exe from here (https://exiftool.org/)
> * place exiftool.exe in Assets directory

Thanks,error message was gone.

**Comment by Maverynthia** [comment]
Thanks, it seems the exiftool included was for an old windows. Needed to be updated from the website you listed.
