### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by thany** [Djdefrag/QualityScaler#79]
Could you add a "getting started" guide? Just a brief (but complete) step-by-step guide from nothing to getting the program doing its thing.

I wouldn't have the first idea how to set this program up. I looks like it's intended for a somewhat novice userbase. Now I'm not going to demand you release a clearly runnable executable or even a setup program, like they do over at Upscayl, but it would be helpful to get some guidelines on how to get started with this piece of software.

For starters, `requirements.txt` looks like ghibberish to me. Not sure what the intention is, but I guess that's an example of what newcomers will likely have trouble with.

**Comment by Djdefrag** [comment]
Hi my friend,

I have added a small guide on how to install everything you need, I hope it helps.

https://github.com/Djdefrag/QualityScaler?tab=readme-ov-file#make-it-work-by-yourself-

**Comment by megarox4u** [comment]
pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, 
or operable program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At line:1 char:1
+ pip install -r requirements
I get this error when i want to install, please help

**Comment by Djdefrag** [comment]
Hi my friend,

have you installed Python? 

are you on Windows?

are you using VSCode as editor?

**Comment by thany** [comment]
There you go, all that is perfect material for a getting started guide.

**Comment by megarox4u** [comment]
> Hi my friend,
> 
> have you installed Python?
> 
> are you on Windows?
> 
> are you using VSCode as editor?

YEAH I HAVE

**Comment by Djdefrag** [comment]
@megarox4u  Hi my friend, can you share a screenshot of your terminal with the error please?

**Comment by TWD97** [comment]
![image](https://github.com/user-attachments/assets/b9d425d4-5e4b-4ac4-9a2f-a4904347fa55)
I too am getting the pip command error, I'm running the latest python package and have the directory open in vscode...
Any ideas?

**Comment by TWD97** [comment]
Hi, I am also getting the pip command error...
![image](https://github.com/user-attachments/assets/20499d03-557e-4593-a518-354ac9aa27af)
Both the latest python and vscode are installed, any ideas?

**Comment by Djdefrag** [comment]
> Hi, I am also getting the pip command error... ![image](https://private-user-images.githubusercontent.com/140716621/357490319-20499d03-557e-4593-a518-354ac9aa27af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NjcxODMsIm5iZiI6MTcyMzU2Njg4MywicGF0aCI6Ii8xNDA3MTY2MjEvMzU3NDkwMzE5LTIwNDk5ZDAzLTU1N2UtNDU5My1hNTE4LTM1NGFjOWFhMjdhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxNjM0NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGJhMzNhM2JmNTk0N2IxNjRiOTIzN2U5NWI4ZGQ3Y2RiMmEwODVlMjRkZWU1YjUwNjg1NTVjMDNjZTgzNjFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qQ07sXxOydezgLYLfG-U5yosg_PJTEJpIxu3PyT25fs) Both the latest python and vscode are installed, any ideas?

Hi my friend,

have you also installed VsCode extension for python?

![image](https://github.com/user-attachments/assets/1bbde541-688b-4e0c-89c8-d295a35d7de4)
