### ISSUE TITLE
Video upscale only exporting audio

### ISSUE THREAD

**Issue by Agr0** [Djdefrag/QualityScaler#82]
When using Quality Scaler application via Steam, I have been trying to upscale some video taken from a DJI OSMO that is saved as an MP4. I am able to select my settings and get the clip to upscale however when it has completed it holds no video and is only an audio file. This has been true on the following models: RealESR_Gx4 and RealSRx4_Anime. I have tried multiple other files and they all have this issue. These videos are being opened in VLC on both x264 and x265

**Comment by Djdefrag** [comment]
hi my friend,

when you upscale videos, a temporary file is created with all video frames in it?

this error happens only with DJI OSMO videos? or also for example a video downloaded from internet?

could you also send me a little clip of one of these videos so I can test what's going on under the hood?

**Comment by Agr0** [comment]
Thank you for the quick response,

This happens on all video files it seems no matter the source. I will try to get you a screenshot of the settings used but please see the link below for the video I have been using.

Memorized settings: RealESR_Gx4, half precision, low interpolation, 100% input res, x265 output.

share.icloud.com/photos/0c3prZQGaOkYZiUblIKNVXKpg

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Djdefrag** [comment]
Hi my friend, 

I have tried both with version 3.7 (the current stable one) and 3.8 that I am developing and everything works. I also send you the link of the video I tested with 25% resolution.

Video link -> https://gofile.io/d/W7pwTX

Can you try it with this resolution as well? Just to see if it is a GPU VRAM memory problem.

In any case can you describe the characteristics of your PC?

**Comment by Agr0** [comment]
Sorry for the delay,

I was able to try the upscale a few more times at multiple resolution levels and it seems that it does successfully complete the job as long as it is under 60% input resolution however seems to be at a significantly lower frame rate than was imported the higher the resolution is. 

This has been tested on 2 different machines with machine #1 being the primary testing machine
1: Intel I5 12600k - 64gb DDR4 3600 - RTX3070 8GB GDDR6
2: Intel I7 9750H - 32GB DDR4 - RTX2080 MAX-Q

**Comment by Djdefrag** [comment]
Hi my friend,

your PCs are perfectly capable of running QualityScaler.

I have a doubt, your pcs both have intel processor with integrated GPU. 
You should check in Windows Task Manager the integrated gpu maybe has index 0 and the dedicated gpu (nvidia) has index 1. 
If this is the case the app uses the integrated GPU and not Nvidia one, you should select GPU 2 from the menu.

![image](https://github.com/user-attachments/assets/3f85a193-5002-46c6-9d3d-dfeab64d5b24)
