### ISSUE TITLE
Can't download AI-onnx.zip

### ISSUE THREAD

**Issue by snwb1nd** [Djdefrag/QualityScaler#83]
Hi @Djdefrag ,

I've been trying to download the file AI-onnx.zip using this link on Gofile: https://gofile.io/d/jbAopi

However, I consistently receive a "502 Bad Gateway" error when I click the download button.

Could you please provide an alternative download link?

Thank you in advance!

**Comment by Djdefrag** [comment]
Hi my friend, 

thanks for reporting the problem.

here the new link: https://gofile.io/d/KEHUMV

**Comment by kdx7214** [comment]
The new link does not work.  I get a bad gateway each time I try to download it.

**Comment by Djdefrag** [comment]
@kdx7214 Hi my friend, re-uploaded.

Here the new LINK - https://gofile.io/d/q4PJW8

**Comment by ewwink** [comment]
Cannot Download, Please reupload to Mega.nz or other place

![image](https://github.com/user-attachments/assets/4659191c-0da5-4163-a433-30251d4bfd45)

**Comment by Djdefrag** [comment]
@ewwink Hi my friend

Re-uploaded - https://gofile.io/d/2RWnDU
