### ISSUE TITLE
Adding our own AI upscale models

### ISSUE THREAD

**Issue by jhitz0z** [Djdefrag/QualityScaler#84]
Is there a way we add and run our own AI .pth models, instead of the current preset models running on this application and the other applications? I'm currently using the windows version of the applications but there is no source file directory .

**Comment by Djdefrag** [comment]
Hi my friend, 

Actually the project does not use .pth files anymore; .pth files have been converted to .onnx files to use onnxruntime.

Of course you can add all AI that you want, if you have .pth files (pytorch models) you have to:

- create a script to convert Pytorch models to onnx models
- add the onnx files in onnx-AI directory of the project
- modify the code adding your AI to the AI list

**Comment by jhitz0z** [comment]
Hello,

And how can I modify the code to add the AI to the AI list?

**Comment by Djdefrag** [comment]
@jhitz0z 

Hi my friend.

After converting your AI model to the onnx format will suffice:

- place the onnx file in the /Ai-onnx folder.
- add the name of your model in the code, specifically in the “AI_models_list” list
