### ISSUE TITLE
Error during upscale process

### ISSUE THREAD

**Issue by Emyssyme** [Djdefrag/QualityScaler#87]
The following output received during upscale process of a video:
Error[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\ExecutionProvider.cpp(923)\onnxruntime_pybind11_state.pyd!00007FFE33F941E2: (caller: 00007FFE33F94BF1) Exception(2) tid(b80) 887A0006 The GPU will not respond to more commands, most likely because of an invalid command passed by the calling application.

Nvidia driver version: 551.61
GPU model: RTX 3060 Laptop GPU
It worked after a second try.

**Comment by Djdefrag** [comment]
Hi my friend,

so on the second attempt there was no problem, right?

Were you using AI multithreading?

**Comment by Emyssyme** [comment]
Hi,

Yes, I used AI multithreading.
Yes, on the second attempt there was no problem.

lun., 22 iul. 2024, 13:14 Annunziata Gianluca ***@***.***> a
scris:
