### ISSUE TITLE
The specified module could not be found. Error loading "torch\lib\caffe2_detectron_ops.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by rmast** [Djdefrag/QualityScaler#9]
I had to download https://aka.ms/vs/16/release/vc_redist.x64.exe on a fresh install of Win10 on a K80 VM to resolve this issue.

**Comment by Djdefrag** [comment]
Hi, thank you. Indeed there might be a dependency on the VisualC++ libraries.
I will try testing QualityScaler on a newly installed Windows without these libraries. Thank you :D

**Comment by rmast** [comment]
I had the message with a Windows 10 pro image on Azure.

**Comment by All-Ki** [comment]
I also had the same error, fixed it by deleting the file.

**Comment by Djdefrag** [comment]
Hi, did you followed the README? :)
