### ISSUE TITLE
message: "Import \"natsort\" could not be resolved - along with 9 other missing imports

### ISSUE THREAD

**Issue by TheFireHedgie** [Djdefrag/QualityScaler#91]
I followed the tutorial step-by-step, downloaded the latest Python (3.11.9), but even after doing the "pip install -r requirements", closing and reopening VSCode, when I click the Play button, I get this error in the terminal: (XXX being my IRL name)

PS C:\Users\XXX\Videos\AI\QualityScaler-3.8> & c:/Users/XXX/Videos/AI/QualityScaler-3.8/.conda/python.exe c:/Users/XXX/Videos/AI/QualityScaler-3.8/QualityScaler.py
Traceback (most recent call last):
  File "c:\Users\XXX\Videos\AI\QualityScaler-3.8\QualityScaler.py", line 42, in <module>
    from natsort import natsorted
ModuleNotFoundError: No module named 'natsort'
PS C:\Users\XXX\Videos\AI\QualityScaler-3.8> 

Uninstalling and re-installing VSCode does not solve the problem, and I didn't found anything on Google. What am I doing wrong?

EDIT - Deleted the .conda folder, solved half of the problems. But I still have these ''missing'', as seen on the screenshot below
![error_python](https://github.com/user-attachments/assets/620def96-8daf-4081-a008-e8e918f0e568)

**Comment by Djdefrag** [comment]
Hi my friend, 

- do you have other Python installed? or just 3.11.9?
- have you downloaded Python - Windows installer (64-bit)?

we can try to clean all package installed and then reinstall again.

in VSCode terminal do this:
- pip freeze > file.txt
- pip uninstall -r file.txt -y
- pip cache purge

this will clean every package installed and now you can reinstall everything with
- pip install -r requirements.txt

be sure to check that this part is successful

**Comment by TheFireHedgie** [comment]
I did everything you mentioned, I still get the same errors, but this time, I have 10 errors rather than 5. Also, VSCode asks to install a virtual environment, either .conda or .venv, which one should I choose?

**Comment by Djdefrag** [comment]
This error is about onnx new version that has some problem, install the previous version with 

pip install onnx==1.16.1

**Comment by TheFireHedgie** [comment]
OK. I did what you said, program boots up, but I get this EVERY TIME I try to upscale:

2024-08-08 04:37:55.0569524 [E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned while running Add node. Name:'/Add' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(2482)\onnxruntime_pybind11_state.pyd!00007FFD49F1C4EF: (caller: 00007FFD49F1DCA1) Exception(11) tid(29e8) 80070057 The parameter is incorrect.

Error[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'/Add' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(2482)\onnxruntime_pybind11_state.pyd!00007FFD49F1C4EF: (caller: 00007FFD49F1DCA1) Exception(9) tid(33e0) 80070057 The parameter is incorrect.

What's wrong?

**Comment by Djdefrag** [comment]
Hi my friend, 

what GPU do you have? do you have multiple GPUs?

are you using default settings?

**Comment by TheFireHedgie** [comment]
Yes. And turns out that the file I was using was a .MKV file of a family's member's wedding in Venice with dual-audio (English-Italian) along with three .SRT files inside, so that might be the problem I had. Now the program runs smoothly, I just have to wait a few hours to see the result.

**Comment by Djdefrag** [comment]
Nice my friend. 

The app also has a STOP&RESUME functionality for videos. 

If you stop the upscaling, and restart it with the same AI and Resolution %,  it will continue.

**Comment by TheFireHedgie** [comment]
Hi! Sorry for the late reply! I was on vacation, and I left my PC opened while I was away. During my vacation, your Python-coded software successfully upscaled my family's wedding Video from 360p to 1080p! My aunt is so happy to have a Hi-Res quality video of her wedding! Now all remaining for me is to author a DVD/Blu-ray of her wedding, but I know how to do it with only freeware :) Your software is approximatively 5 times faster than other AI Upscaling software (including shareware trials). I HIGHLY recommend it! Thank you, from both me and my family!

**Comment by Djdefrag** [comment]
HI! Thank you my friend :D
